version: 2.1
jobs:
  haskell-build:
    working_directory: /root/CurrryMud
    docker:
      - image: haskell:8
    steps:
      - checkout 
      - run: |
          echo $HOME
          pwd
          ls -al
          stack setup
          stack build
          stack install
         
workflows:
  build-test-deploy:
    jobs:
      - haskell-build
