version: 2.1
jobs:
  build:
    docker:
      - image: haskell:8
    steps:
      - run: |
          echo $HOME
          pwd
          ls -al
          stack setup
          stack build
          stack install
