version: 2.1
jobs:
  haskell-build:
    working_directory: /root/CurryMud
    docker:
      - image: haskell:8
    steps:
      - checkout 
      - run: |
          apt install -y libpcre3 libpcre3-dev
          stack setup
          stack build
          stack install
         
workflows:
  build-test-deploy:
    jobs:
      - haskell-build
