version: 2.1
jobs:
  curry-build:
    working_directory: /root/CurryMUD
    docker:
      - image: haskell:8
    steps:
      - checkout 
      - run: |
          apt update
          apt install -y libpcre3 libpcre3-dev
          stack setup
          stack build
          stack install
      - run: |
          cd /root
          tar czvf CurryMUD.tar.gz ./CurryMUD/

      - store_artifacts:
          path: /root/.local/bin/curry
          destination: curry

      - store_artifacts:
          path: /root/CurryMUD.tar.gz
          destination: CurryMUD.tar.gz
         
workflows:
  build-test-deploy:
    jobs:
      - curry-build
